services:
  db:
    image: postgres:16.1
    container_name: postgres-16.1-rr8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_USER=pikujags
      - POSTGRES_PASSWORD=pikujags
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-dev-rr8
    # Remove the below line if you want to use the default command from Dockerfile
    # To access localhost for development we have to specify -b 0.0.0.0 in the command
    # command : "./bin/rails server -b 0.0.0.0 -p 80"
    # command: "./bin/rails server -p 80"
    environment:
      - RAILS_ENV=development # Hardcoded env variable for development as this docker compose file specific for development only,
      # so no need for pass this from env
      # - RAILS_MASTER_KEY=${RAILS_MASTER_KEY} # This variable is only needed in prod rails environment
      # - POSTGRES_HOST=db
      # - POSTGRES_USER=pikujags
      # - POSTGRES_PASSWORD=pikujags
      # - POSTGRES_DB=${POSTGRES_DB}
      # - FIREWORKS_AI_API_KEY=${FIREWORKS_AI_API_KEY}
      # - FIREWORKS_AI_TEXT_API_URL=${FIREWORKS_AI_TEXT_API_URL}
      # - FIREWORKS_AI_IMAGE_API_URL=${FIREWORKS_AI_IMAGE_API_URL}
      # - OVERMIND_PORT=${OVERMIND_PORT}
      # - OVERMIND_SOCKET=${OVERMIND_SOCKET}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "80:80"

volumes:
  postgres_data: {}
  app-storage: {}
