default: &default
  adapter: "postgresql"
  encoding: "unicode"
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "postgres" } unless ENV["RAILS_ENV"] == "development" %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "sample_app_db" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "sample_app_db" } %>_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB") { "sample_app_db" } %>_production
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB") { "sample_app_db" } %>_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB") { "sample_app_db" } %>_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB") { "sample_app_db" } %>_production_cable
    migrations_paths: db/cable_migrate
