default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") if ENV["POSTGRES_HOST"]%>
  username: <%= ENV.fetch("POSTGRES_USER") if ENV["POSTGRES_USER"] %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") if ENV["POSTGRES_PASSWORD"]%>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") if ENV["POSTGRES_DB"] %>_dev

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB") if ENV["POSTGRES_DB"] %>_prod
  cache:
    <<: *primary_production
    database: rr8_dc_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rr8_dc_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rr8_dc_production_cable
    migrations_paths: db/cable_migrate
